### ISSUE TITLE
Any specific reason why this repo is no longer updated?

### ISSUE THREAD

**Issue by Nixtren** [BitGo/bitgo-chrome#1]
Hey,

I'm just curious to know why this repository is no longer updated when a new BitGo Chrome app is released on the Chrome Store. Did it go closed-source?

Thanks.

**Comment by jlopp** [comment]
Hi @Nixtren, we do our development in a different private repository and then copy over the source manually when we release it. It looks like the repo copy step was neglected for the past few releases; thanks for the heads up. This should be up-to-date with https://github.com/BitGo/bitgo-chrome/commit/3e3a069bcf154022e6b157ad57b25a7e0d12c5f3
